/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <SpriteKit/SKTextureAtlas.h>

@interface SKTextureAtlas (Internal)
+ (id)findTextureNamed:(id)arg1;
+ (id)getSupportedPostfixes;
- (void)unload;
- (void)preload;
@end

